import type { AuditEvidence } from "@/lib/api";

/**
 * Plain calculations over the retrieved posts and reviews. Nothing here is
 * generated by a model — every number on the evidence views comes from this.
 */

export const WEEKDAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

const TYPE_LABEL: Record<string, string> = {
  image: "Photo",
  reel: "Reel",
  video: "Video",
  carousel: "Carousel",
  story: "Story",
  unknown: "Other",
};
export const typeLabel = (t: string) => TYPE_LABEL[t] ?? t.charAt(0).toUpperCase() + t.slice(1);

export type EvidenceStats = {
  postCount: number;
  reviewCount: number;
  weekday: number[]; // Mon..Sun counts
  postsPerWeek: number | null;
  quietDays: string[];
  byType: { type: string; count: number; avgEngagement: number; avgComments: number }[];
  topType: { type: string; avgEngagement: number } | null;
  avgEngagement: number | null;
  ratings: number[]; // index 0 = 1 star … 4 = 5 stars
  avgRating: number | null;
  replyRate: number | null;
};

export function computeStats(ev: AuditEvidence): EvidenceStats {
  const dated = ev.posts.filter((p) => p.posted_at);
  const weekday = [0, 0, 0, 0, 0, 0, 0];
  dated.forEach((p) => {
    const d = new Date(p.posted_at!).getDay(); // 0 = Sun
    weekday[(d + 6) % 7] += 1;
  });

  let postsPerWeek: number | null = null;
  if (dated.length) {
    const times = dated.map((p) => new Date(p.posted_at!).getTime());
    const spanWeeks = Math.max(1, (Math.max(...times) - Math.min(...times)) / (7 * 86_400_000));
    postsPerWeek = Math.round((dated.length / spanWeeks) * 10) / 10;
  }

  const min = Math.min(...weekday);
  const quietDays = dated.length ? WEEKDAYS.filter((_, i) => weekday[i] === min) : [];

  const groups = new Map<string, { n: number; eng: number; com: number }>();
  ev.posts.forEach((p) => {
    const g = groups.get(p.media_type) ?? { n: 0, eng: 0, com: 0 };
    g.n += 1;
    g.eng += p.likes + p.comments;
    g.com += p.comments;
    groups.set(p.media_type, g);
  });
  const byType = Array.from(groups.entries())
    .map(([type, g]) => ({ type, count: g.n, avgEngagement: Math.round(g.eng / g.n), avgComments: Math.round((g.com / g.n) * 10) / 10 }))
    .sort((a, b) => b.avgEngagement - a.avgEngagement);

  const totalEng = ev.posts.reduce((s, p) => s + p.likes + p.comments, 0);
  const ratings = [0, 0, 0, 0, 0];
  ev.reviews.forEach((r) => {
    if (r.rating >= 1 && r.rating <= 5) ratings[r.rating - 1] += 1;
  });

  return {
    postCount: ev.posts.length,
    reviewCount: ev.reviews.length,
    weekday,
    postsPerWeek,
    quietDays,
    byType,
    topType: byType[0] && byType.length > 1 ? { type: byType[0].type, avgEngagement: byType[0].avgEngagement } : null,
    avgEngagement: ev.posts.length ? Math.round(totalEng / ev.posts.length) : null,
    ratings,
    avgRating: ev.reviews.length ? Math.round((ev.reviews.reduce((s, r) => s + r.rating, 0) / ev.reviews.length) * 10) / 10 : null,
    replyRate: ev.reviews.length ? ev.reviews.filter((r) => r.owner_replied).length / ev.reviews.length : null,
  };
}

const SOURCE_LABEL: Record<string, string> = {
  instagram: "Instagram",
  facebook: "Facebook",
  google_reviews: "Google reviews",
  google_business: "Google Business listing",
};
export const sourceLabel = (s: string) => SOURCE_LABEL[s] ?? s;

export const agentLabel = (name: string) =>
  name
    .split("_")
    .map((w, i) => (i === 0 ? w.charAt(0).toUpperCase() + w.slice(1) : w))
    .join(" ");

export const toolLabel = (t: string) =>
  ({ owner_social_data_retrieval: "Read your collected social data", market_data_retrieval: "Read local market data", competitor_data_retrieval: "Read competitor data" } as Record<string, string>)[t] ??
  t.replace(/_/g, " ");

export function ago(iso: string | null) {
  if (!iso) return "unknown";
  const h = Math.max(0, Math.round((Date.now() - new Date(iso).getTime()) / 3_600_000));
  if (h < 1) return "just now";
  if (h < 24) return `${h}h ago`;
  return `${Math.round(h / 24)}d ago`;
}
